### ISSUE TITLE
Why can it run on a CPU that does not support AVX2?

### ISSUE THREAD

**Issue by zzjianhui** [Triple-Z/AVX-AVX2-Example-Code#1]
My CPU does not support AVX2, only support AVX. But it can run hadds.

**Comment by Triple-Z** [comment]
Which CPU micro-architecture are you using?

Maybe you should check this: https://community.intel.com/t5/Intel-C-Compiler/Illegal-instruction-when-running-AVX-program/td-p/1022837 .

**Comment by Triple-Z** [comment]
Closed due to inactive for over three months.
